### ISSUE TITLE
Rename effects in the BackendEffect from `Secret` to`Entry`

### ISSUE THREAD

**Issue by MagicRB** [serokell/coffer#20]
`readSecret` and so on don't precisely reflect the terminology we have agreed on. Changing them now would be a rather large change which would effect the whole codebase. Therefore we should wait for the `"big merge" until we tackle this.

**Comment by sancho20021** [comment]
Do we need to rename all occurrences of word `secret` to `entry` in our project?

**Comment by sancho20021** [comment]
@dcastro or @MagicRB , I made a draft pull request, cause I'm unsure whether my changes properly fix this issue. Please, have a look.
