### ISSUE TITLE
Make code conform to Serokell style policies.

### ISSUE THREAD

**Issue by Heimdell** [serokell/coffer#28]
The code style (including points that `stylish-haskell` cannot fix by itself) does not conform to https://github.com/serokell/style/blob/master/haskell.md.

We should apply the code style referenced above with enabling `BlockArguments`, `LambdaCase` and `ImportQualfiedPost` inside our copy of style configuration file.

**Comment by dcastro** [comment]
Thanks for creating this issue!

I've added the `code_style.md` file to the repo in #27

I've also added a note to #26 to not add stylish-haskell/hlint until #7 (and #27) is merged to avoid more conflicts.
