### ISSUE TITLE
Merge `--filter` and `--filter-field` into one option in core, CLI and web API

### ISSUE THREAD

**Issue by Heimdell** [serokell/coffer#44]
# Clarification and motivation

@dcastro: I think the --filter and --filter-field options can be merged into a single --filter option.

e.g.:
```
--filter name~vault               <- filter entries by entry name
--filter url:value~google.com     <- filter entries by field value
```

Probably, multiple `--filter` in CLI should act all at once, and so do `filter[]=...` in web API.

# Acceptance criteria

- [ ] core has them merged
- [ ] CLI has them merged
- [ ] web API has them merger

**Comment by dcastro** [comment]
Looks like the core + cli have been updated in #94, and the web API has been updated during the last rebase in #37. Closing this issue now.
