### ISSUE TITLE
Read backend configs from a file

### ISSUE THREAD

**Issue by dcastro** [serokell/coffer#84]
This issue is blocked by https://github.com/serokell/coffer/pull/37.

# Clarification and motivation

Right now the Web API takes a vault token via a header. This is a problem on two levels:

* It can only work with vault backends (and not with, e.g., pass backends)
* We shouldn't expect the client to tell the server which backend it needs to connect to. The server should read its own config from some `config.toml`.

The location of the config file should be configurable via a command line option or an env variable (just like the CLI)

The Web API should take qualified paths. The client can tell the API which backend to connect to by using a qualified path.

# Acceptance criteria

* The Web API reads its config from a file
* The config filepath is configurable
* The Web API takes qualified paths

**Comment by MagicRB** [comment]
How do we handle multi user servers? If there is only one global config Alice could access Bobs secret.

**Comment by dcastro** [comment]
> How do we handle multi user servers? If there is only one global config Alice could access Bobs secrets.

That's a very good question - I guess we haven't discussed authorization/authentication at all yet. We should discuss this in Slack with @notgne2, and the grand scheme of things (e.g. how will users authenticate in the frontend?)

**Comment by dcastro** [comment]
Looks like @DK318 already did this in #37, closing this issue.

Nevertheless, a larger discussion still needs to happen.
