### ISSUE TITLE
Make the port number configurable

### ISSUE THREAD

**Issue by dcastro** [serokell/coffer#85]
# Clarification and motivation

The port that servant will list on should be configurable, via a command-line option or an env variable.

The command-line option should take precedence over the env variable.

# Acceptance criteria

* The port number is configurable

**Comment by Kariel-Myrr** [comment]
What we're doing if port wasn't specified nor by cmd option, nor by env var

**Comment by dcastro** [comment]
I'd say we should fail and tell the user to specify a port and how to do it.
